# 1. Create a 3x3x3 array with random values 

In [8]:
## We import the numpy library
import numpy as np
td_array = np.array([[[9,10,11],[12,13,14],[15,16,17]],[[1,2,3],[3,4,5],[6,7,8]]])
td_array

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [13]:
fmatrix = np.diag(np.arange(5),-1) # This will give the elements 0,1,2,3,4 just below the main diagonal 
fmatrix

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
# We get the checkerboard pattern for a matrix by taking 0s as black and 1s as whites
import numpy as np
# First we initialise a 8x8 matrix with 0 values all over
cb = np.zeros((8,8))
cb[1::2, ::2] = 1 #  First we access the alternate matrices and fill them with alternate 1s
cb[::2, 1::2] = 1 # This does the same for the remaining matrices
cb



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [23]:
x= np.random.random((5,5))
print("The original 2D array : ")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin) # The formula for normalizatiom
print("After normalization:")
print(x)

The original 2D array : 
[[0.80620486 0.4042034  0.18403207 0.34047949 0.0112195 ]
 [0.81134573 0.42312719 0.53802267 0.95076309 0.8927723 ]
 [0.19877383 0.76513955 0.22840778 0.40746535 0.37147817]
 [0.53762922 0.91150026 0.65315776 0.76425733 0.76078198]
 [0.14313198 0.86596177 0.47062621 0.87763047 0.03634445]]
After normalization:
[[0.84613994 0.41827106 0.18393247 0.35044674 0.        ]
 [0.85161161 0.43841253 0.56070115 1.         0.9382777 ]
 [0.1996228  0.80243222 0.23116361 0.42174291 0.38344008]
 [0.56028238 0.95821073 0.68324479 0.80149323 0.79779426]
 [0.1404006  0.909742   0.48896796 0.92216154 0.02674165]]


# 5.  How to find common values between two arrays?

In [24]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,3,10])
for i in x2:
    if i in x1:
        print("The common element is : ", i)

The common element is :  3


# 6.How to get the dates of yesterday, today and tomorrow?

In [25]:
# For this problem we use the numpy datetime64() and timedelta64() from numpy
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [3]:
A = np.random.randint(0,2,6)
print("First array:")
print(A)
B = np.random.randint(0,2,6)
print("Second array:")
print(B)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(A, B)
print(array_equal)

First array:
[0 1 0 0 1 1]
Second array:
[1 0 0 1 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [4]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[0.59800206 0.53977592 0.12068063 0.8650653  0.40575316 0.57049029
 0.2175149  0.46057848 0.69848194 0.53526413]
Maximum value replaced by 0:
[0.59800206 0.53977592 0.12068063 0.         0.40575316 0.57049029
 0.2175149  0.46057848 0.69848194 0.53526413]


# 9. How to print all the values of an array?

In [9]:
x = np.random.random(10)
for i in range(len(x)):
    print(x[i], end = " ")

0.137976406211192 0.36908133543342425 0.3069941777297541 0.5560066948113048 0.04954125131365961 0.5927917315550737 0.5105138675024095 0.511734094877637 0.7279945583939333 0.2820337392477008 

# 10.Subtract the mean of each row of a matrix

In [10]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\n Subtract the mean of each row of the said matrix:\n")
Y = X - X.mean()
print(Y)

Original matrix:

[[0.5078569  0.0764664  0.30757686 0.98912541 0.68838132 0.33587967
  0.89572109 0.26462343 0.50292331 0.80328734]
 [0.84412443 0.26682788 0.88974143 0.46765934 0.47297429 0.1758702
  0.31726229 0.93969414 0.4227162  0.0612002 ]
 [0.67437694 0.07282862 0.26999717 0.42249506 0.92774911 0.27763312
  0.66642696 0.40917869 0.94801301 0.39634809]
 [0.96856066 0.832564   0.22470215 0.33781591 0.864928   0.57579485
  0.99257165 0.79072038 0.34776313 0.35500301]
 [0.37691039 0.46052195 0.83736734 0.24223934 0.7839127  0.41688202
  0.90189746 0.49780496 0.19028034 0.25237397]]

 Subtract the mean of each row of the said matrix:

[[-0.02305456 -0.45444507 -0.2233346   0.45821394  0.15746986 -0.1950318
   0.36480963 -0.26628803 -0.02798815  0.27237588]
 [ 0.31321297 -0.26408358  0.35882997 -0.06325213 -0.05793717 -0.35504127
  -0.21364918  0.40878267 -0.10819526 -0.46971126]
 [ 0.14346548 -0.45808284 -0.26091429 -0.10841641  0.39683765 -0.25327834
   0.1355155  -0.12173277  0.41

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [ ]:
result=np.empty([n,], dtype=A.dtype )
for i in xrange(n):
    result[i]=A[i,:].dot(B).dot(A[i,:])

# 13.How to find the most frequent value in an array?

In [17]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[0 0 7 5 0 9 3 5 6 4 5 6 6 5 7 7 2 1 0 4 7 9 1 5 8 5 8 1 1 2 0 2 5 7 7 7 3
 7 9 9]
Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [21]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = int(input("Enter the number of largest values : "))
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
Enter the number of largest values : 3
[7 8 9]


# 15.How to create a record array from a regular array?

In [22]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
